[project]
name = "superdator-inference-client"
dynamic = ["version"]
description = "Client library for communicating with the superdator-inference server"
requires-python = ">=3.9"
dependencies = [
    "opencv-python",
    "numpy",
    "websocket-client",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
raw-options = { root = ".." }

[tool.hatch.build.targets.wheel]
packages = ["src/superdator_client"]
